services:
  redis:
    container_name: redis
    image: redis:7.2.1-alpine
    restart: always
    ports:
    - 6379:6379
    volumes:
    - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
    name: scoring-service-redis-data
