repos:
- repo: https://github.com/humitos/mirrors-autoflake
  rev: v1.3
  hooks:
    - id: autoflake
      args:
        [
          "--exclude",
          ".venv",
          "--in-place",
          "--remove-all-unused-imports",
          "--remove-unused-variable",
          "--ignore-init-module-imports",
          "-r",
        ]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: check-added-large-files
    exclude: (grafana|accommodations)
  - id: end-of-file-fixer
  - id: trailing-whitespace
    exclude: (README.md)

- repo: https://github.com/psf/black
  rev: 23.9.0
  hooks:
  - id: black
    exclude: (alembic)
    language_version: python3.10
    args: [--line-length=120]

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: isort
    exclude: (alembic)
    args:
      [
        --profile,
        black,
        --line-length=120,
        --combine-as,
        --split-on-trailing-comma,
      ]

- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    args: [--max-line-length=120]
    exclude: (alembic)

- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.1.0
  hooks:
  - id: add-trailing-comma

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: pretty-format-yaml
    exclude: (.pre-commit-config.yaml)
    args:
    - --autofix
    - --preserve-quotes
    - --indent=2
