"""empty message

Revision ID: 01
Revises:
Create Date: 2024-09-20 17:23:07.980885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'accommodation',
        sa.Column('type', sa.String(length=64), nullable=False),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('slug', sa.String(length=512), nullable=False),
        sa.Column('stars', sa.SmallInteger(), nullable=False),
        sa.Column('zip_code', sa.String(length=16), nullable=False),
        sa.Column('street', sa.String(length=1028), nullable=False),
        sa.Column('phone', sa.String(length=32), nullable=False),
        sa.Column('email', sa.String(length=512), nullable=False),
        sa.Column('url', sa.String(length=1028), nullable=False),
        sa.Column('is_bookable', sa.Boolean(), nullable=False),
        sa.Column('latitude', sa.Float(), nullable=False),
        sa.Column('longitude', sa.Float(), nullable=False),
        sa.Column('zoover_gold_award', sa.Boolean(), nullable=False),
        sa.Column('zoover_silver_award', sa.Boolean(), nullable=False),
        sa.Column('default_price', sa.Integer(), nullable=False),
        sa.Column('facts', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('name'),
        sa.UniqueConstraint('phone'),
        sa.UniqueConstraint('slug'),
    )
    op.create_table(
        'amenity',
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'award',
        sa.Column('rank', sa.SmallInteger(), nullable=False),
        sa.Column('type', sa.String(length=16), nullable=False),
        sa.Column('is_region', sa.Boolean(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'distance',
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'domain',
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'holiday_type',
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'locale',
        sa.Column('code', sa.String(length=5), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code'),
    )
    op.create_table(
        'source',
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'theme',
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('is_static', sa.Boolean(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'user',
        sa.Column('name', sa.String(length=512), nullable=False),
        sa.Column('email', sa.String(length=512), nullable=False),
        sa.Column('ip_address', sa.String(length=64), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )
    op.create_table(
        'accommodation__amenity',
        sa.Column('accommodation_id', sa.UUID(), nullable=False),
        sa.Column('amenity_id', sa.UUID(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['accommodation_id'], ['accommodation.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['amenity_id'], ['amenity.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('accommodation_id', 'amenity_id', 'id'),
    )
    op.create_table(
        'accommodation__award',
        sa.Column('accommodation_id', sa.UUID(), nullable=False),
        sa.Column('award_id', sa.UUID(), nullable=False),
        sa.Column('year', sa.SmallInteger(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['accommodation_id'], ['accommodation.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['award_id'], ['award.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('accommodation_id', 'award_id', 'id'),
    )
    op.create_table(
        'accommodation__distance',
        sa.Column('accommodation_id', sa.UUID(), nullable=False),
        sa.Column('distance_id', sa.UUID(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['accommodation_id'], ['accommodation.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['distance_id'], ['distance.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('accommodation_id', 'distance_id', 'id'),
    )
    op.create_table(
        'accommodation__domain',
        sa.Column('accommodation_id', sa.UUID(), nullable=False),
        sa.Column('domain_id', sa.UUID(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['accommodation_id'], ['accommodation.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('accommodation_id', 'domain_id', 'id'),
    )
    op.create_table(
        'accommodation__holiday_type',
        sa.Column('accommodation_id', sa.UUID(), nullable=False),
        sa.Column('holiday_type_id', sa.UUID(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['accommodation_id'], ['accommodation.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['holiday_type_id'], ['holiday_type.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('accommodation_id', 'holiday_type_id', 'id'),
    )
    op.create_table(
        'accommodation__theme',
        sa.Column('accommodation_id', sa.UUID(), nullable=False),
        sa.Column('theme_id', sa.UUID(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['accommodation_id'], ['accommodation.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['theme_id'], ['theme.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('accommodation_id', 'theme_id', 'id'),
    )
    op.create_table(
        'file',
        sa.Column('source_url', sa.Text(), nullable=False),
        sa.Column('rotation_degrees', sa.Boolean(), nullable=True),
        sa.Column('title', sa.String(length=256), nullable=False),
        sa.Column('is_top', sa.Boolean(), nullable=False),
        sa.Column('is_default', sa.Boolean(), nullable=False),
        sa.Column('accommodation_id', sa.UUID(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['accommodation_id'], ['accommodation.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'review',
        sa.Column('title', sa.String(length=128), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('travel_date', sa.String(length=8), nullable=True),
        sa.Column('travel_party', sa.String(length=128), nullable=True),
        sa.Column('general_score', sa.Float(), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('zoover_review_id', sa.Integer(), nullable=False),
        sa.Column('score_aspects', sa.JSON(), nullable=False),
        sa.Column('accommodation_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('locale_id', sa.UUID(), nullable=True),
        sa.Column('source_id', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['accommodation_id'], ['accommodation.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['locale_id'], ['locale.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('file')
    op.drop_table('accommodation__theme')
    op.drop_table('accommodation__holiday_type')
    op.drop_table('accommodation__domain')
    op.drop_table('accommodation__distance')
    op.drop_table('accommodation__award')
    op.drop_table('accommodation__amenity')
    op.drop_table('user')
    op.drop_table('theme')
    op.drop_table('source')
    op.drop_table('locale')
    op.drop_table('holiday_type')
    op.drop_table('domain')
    op.drop_table('distance')
    op.drop_table('award')
    op.drop_table('amenity')
    op.drop_table('accommodation')
    # ### end Alembic commands ###
